twitter_consumer_key= XLHPDF6tBcJ1ZeAQb6glOA
twitter_consumer_secret= jCkG3X9284vrxJhZOJRCRyP8P66YjwaAHVwduSvE0Y
facebook_key= 123240354547491
facebook_secret= 6cdde90dc74bdfa9dd52b230c7803b0e
stripe_connect_client_id= ca_1vEYPeo1zAz5VmekvsxNsiqZRfrjas2o
stripe_test_secret_key= sk_test_LV8aFHkIXMw6dFXUjrcSQ3St
AWS_ACCESS_KEY_ID= AKIAJE2ORZPS57D3R2MA
AWS_SECRET_ACCESS_KEY= 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
AWS_BUCKET_NAME= Hopelauncher-Test