theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - advlist
  - anchor
  - autolink
  - autoresize
  - autosave
  - bbcode
  - charmap
  - code
  - compat3x
  - contextmenu
  - directionality
  - emoticons
  - example
  - example_dependency
  - fullpage
  - fullscreen
  - hr
  - image
  - insertdatetime
  - layer
  - legacyoutput
  - link
  - lists
  - media
  - nonbreaking
  - noneditable
  - pagebreak
  - paste
  - preview
  - print
  - save
  - searchreplace
  - spellchecker
  - tabfocus
  - table
  - template
  - textcolor
  - visualblocks
  - visualchars
  - wordcount